#!/bin/bash

set -Eeuo pipefail

packages=(
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-annotations
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-annotations-spring
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-browser-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-browser-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-charts
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-charts-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-charts-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-browser
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-charts
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-deck
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-diagrams
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-formdescriptioneditors
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-formdescriptioneditors-widget-reference
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-formdescriptioneditors-widget-table
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-forms
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-gantt
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-portals
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-selection
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-tables
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-trees
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-validation
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-widget-reference
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-collaborative-widget-table
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-core
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-core-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-core-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-deck
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-deck-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-deck-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-diagrams
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-diagrams-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-diagrams-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-diagrams-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-domain
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-domain-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-domain-emf
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-domain-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-emf
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-emf-forms
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-emf-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-emf-tables
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-events
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-flow-starter
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-formdescriptioneditors
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-formdescriptioneditors-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-formdescriptioneditors-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-forms
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-forms-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-forms-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-forms-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-gantt
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-gantt-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-gantt-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-gantt-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-graphql-api
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-graphql-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-interpreter
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-papaya
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-papaya-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-papaya-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-portals
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-portals-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-portals-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-portals-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-releng-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-representations
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-selection
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-selection-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-selection-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-spring-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-starter-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-tables
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-tables-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-tables-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-tables-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-task
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-task-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-task-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-task-starter
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-test-coverage
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-tests-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-trees
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-trees-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-trees-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-trees-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-validation
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-validation-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-validation-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-builder
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-builder-generator
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-deck
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-deck-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-diagram
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-diagram-customnodes
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-diagram-customnodes-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-diagram-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-emf
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-emf-widget-reference
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-emf-widget-table
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-form
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-form-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-gantt
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-gantt-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-table
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-table-customcells
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-table-customcells-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-table-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-tree
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-view-tree-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-web
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-web-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-reference
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-reference-graphql
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-reference-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-reference-view
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-reference-view-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-table
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-table-view
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-components-widget-table-view-edit
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-application
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-domain
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-e2e-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-frontend
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-infrastructure
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-papaya
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-parent
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-root
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-starter
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-tests
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-tests-data
https://api.github.com/orgs/metamodeldev/packages/maven/org.eclipse.sirius.sirius-web-view-fork
)

for pkg in ${packages[@]}; do
  echo "Deleting $pkg"
  curl -L \
    -X DELETE \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer $GITHUB_DELETE_TOKEN" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "$pkg"
done
