name: Maven Publish

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java SDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Maven Build
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{secrets.GITHUB_TOKEN}}
        run: mvn -U -B clean verify -f backend/pom.xml --settings settings.xml

      - name: Maven Deploy
        if: (github.event_name == 'push' || github.event_name == 'workflow_dispatch')  && github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: mvn -B deploy -f backend/pom.xml
